# Generated by Django 2.2.12 on 2021-11-09 10:22

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_mentor',
            field=models.BooleanField(default=False, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
