# Generated by Django 2.2.12 on 2021-11-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211109_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_student',
        ),
    ]
